### ISSUE TITLE
Research new template

### ISSUE THREAD

**Issue by kandalf** [threefunkymonkeys/funky-world-cup#155]
Research for Bootstrap templates for the new FWC UI.

Assess the feasibility of a dashboard-admin-like UI

**Comment by kandalf** [comment]
I really liked this one: https://www.creative-tim.com/product/vue-light-bootstrap-dashboard-pro

It's a paid template, $49, but it looks pretty nice to me, it uses VueJS which is something we've discussed for this refactor and it doesn't look too overloaded of stuff.

**Comment by tarolandia** [comment]
Looks great! My only concern is that this is a public repo and we will be sharing a paid template source code. We should check terms and conditions first.

**Comment by kandalf** [comment]
Alright, after discussing it over Slack, we decided to buy the template since we're not going to expose the template as a package nor the plain files but only our application of the template within our app.

The template has been already bought, I'll share it privately when we start to implement the new UI.

**Comment by tarolandia** [comment]
Awesome!
