### ISSUE TITLE
Discuss: New login page

### ISSUE THREAD

**Issue by tarolandia** [threefunkymonkeys/funky-world-cup#159]
Let's discuss ideas to replace our old login page:

![old-login](https://user-images.githubusercontent.com/357127/36783850-2b680776-1c5c-11e8-93e5-5296c4f9d264.png)

The new template has some login/register examples, but I was not convinced by an of them. Since we use twitter and facebook for quick login/register, we might need to design this new page a little more.

Ideas?

**Comment by kandalf** [comment]
@tarolandia Maybe something like this:

![login](https://user-images.githubusercontent.com/43977/36924241-a3a418e6-1e4c-11e8-8922-77a82f4454ec.png)

Of course we'll need to implement something with the template styles to see exactly how it would look, this image is just intended to show the distribution of elements in this screen.

I'm not sure about the background, though, maybe we can try with some plain color, one of the FWC logo or the one we used for the landing page....

This is just the first approach that came to my mind, feel free to disregard if you don't like it.

Thoughts?

**Comment by kandalf** [comment]
We might also need to look for more modern icons for Facebook / Twitter

**Comment by tarolandia** [comment]
I was thinking that we could look for a different background image (a free one), or leave the backgound white or grey. I think logo's colors are too bright to use as bg color.

**Comment by kandalf** [comment]
That's a good point. Do you have some type of image in mind?
Otherwise, maybe we can play around with some colors and make some proofs of concept....

**Comment by tarolandia** [comment]
Maybe some photo related to Russia? 

https://pixabay.com/en/moscow-st-basile-red-square-church-2742642/
https://pixabay.com/en/moscow-convent-orthodox-church-1926621/
https://pixabay.com/en/russia-moscow-the-kremlin-panorama-2123697/
https://pixabay.com/en/st-petersburg-russia-nonoj-petersburg-1034319/
https://pixabay.com/en/saint-petersburg-stadium-fifa-2018-1891979/

**Comment by tarolandia** [comment]
This is an example with one of those images
![login-bg](https://user-images.githubusercontent.com/357127/37061672-f30a10e2-2172-11e8-84f6-0b4acef2622f.png)

**Comment by kandalf** [comment]
I love it.
Great pictures. I'm having a hard time to pick one, maybe we could use a set of images and show one randomly... just an idea, but yeah, we should definitely use an Russia related image for this.
