### ISSUE TITLE
Refactor: Show rules

### ISSUE THREAD

**Issue by tarolandia** [threefunkymonkeys/funky-world-cup#161]
User model has a `show_rules` flag that will be used by the application to show the rules in the dashboard for new users. Once the user clicks `Got it` or the link in the description, the flag is set to false.

With the new template, I'd refactor this behavior to use a Notification and place it at the top of the Dashboard.
![notifications](https://user-images.githubusercontent.com/357127/36784930-e7727b74-1c5f-11e8-86d5-6a701fcf48ab.png)

Once the user dismiss the notification, we set the flag to false.

**Comment by kandalf** [comment]
I totally agree. Great idea.
