### ISSUE TITLE
Discuss: Right Sidebar

### ISSUE THREAD

**Issue by tarolandia** [threefunkymonkeys/funky-world-cup#162]
Current layout has a right sidebar with some general information: Rank, Point, Groups and Share links.

I think score, rank and groups are things we can have in the Dashboard view, but we don't need for other pages. And share links can be placed either in the new left sidebar or in the header.

I'd like to suggest removing this right sidebar, leaving more room for re-designing sections like Positions table, predictions, fixture, etc.

@kandalf thoughts?

**Comment by kandalf** [comment]
@tarolandia I've been thinking in something like this:

![sidebar](https://user-images.githubusercontent.com/43977/36923241-660377a0-1e49-11e8-91f2-8fbf72f33bf9.png)

The icon in the top right would be a quick access to create a new group.

The rest of the old top bar is moved to the left sidebar.

**Comment by tarolandia** [comment]
I like it. Should we keep translation flags visible in the header? or are they hidden in that menu?

**Comment by kandalf** [comment]
No, I missed the lang flags, they should go in the header for a better visbility.
