### ISSUE TITLE
Apply new template to static pages

### ISSUE THREAD

**Issue by kandalf** [threefunkymonkeys/funky-world-cup#179]
Implement the static pages for `Disclaimer`, `Rules` and `Terms Of Service` with the new template style.

**Comment by kandalf** [comment]
This is how it's looking so far:

![image](https://user-images.githubusercontent.com/43977/38614501-c7f24372-3d63-11e8-8167-751b5de1a32b.png)

I'm trying to place the Paypal logo in the footer, but I'm failing successfully so far.

**Comment by tarolandia** [comment]
Looks great! If Paypal logo is blocking you, forget about it. We will find a good place for it later.
