### ISSUE TITLE
Check warning color of predictions modal

### ISSUE THREAD

**Issue by kandalf** [threefunkymonkeys/funky-world-cup#228]
It was given some feedback about the alert in the predictions modal that it doesn't look too important when it actually is.

![image](https://user-images.githubusercontent.com/43977/40518217-e4664758-5f8f-11e8-832c-2200b4f10a10.png)

The template coloring provides this other color for `danger` alerts:

![image](https://user-images.githubusercontent.com/43977/40518236-fa5b1eee-5f8f-11e8-83e2-686b4d1cfa6a.png)

I'm still undecided, but it kind of makes sense to make it look as important as possible since you can't change your predictions once submitted.

@tarolandia thoughts?

**Comment by tarolandia** [comment]
Honestly, I think the warning message is as visible as it could be, plus it's located between inputs and buttons.

**Comment by kandalf** [comment]
Yeah, I agree, let's keep it as it is now.

Thank you for your input!
